name: Java Ant Build and Test

'on':
  push:
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Clean previous build artifacts
        run: ant clean

      - name: Build and run tests
        id: run-tests
        run: |
          ant test || echo "BUILD_FAILED=true" >> $GITHUB_ENV
        continue-on-error: true

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Create Issue with Test Results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ env.BUILD_FAILED }}" == "true" ]; then
            ISSUE_TITLE="Falló la compilación de las pruebas unitarias - $CURRENT_DATE"
            ISSUE_BODY="La compilación de las pruebas unitarias falló. Por favor, revisa los logs de GitHub Actions para más detalles."
          else
            ISSUE_TITLE="Éxito en la compilación de las pruebas unitarias - $CURRENT_DATE"
            ISSUE_BODY="Todas las pruebas unitarias se completaron correctamente."
          fi
          curl \
            -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d "{\"title\":\"$ISSUE_TITLE\",\"body\":\"$ISSUE_BODY\"}"
